name: virtual-env

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/virtual-env.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/virtual-env.yml'

jobs:
  os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      -
        name: File system
        run: df -ah
      -
        name: Mounts
        run: mount
      -
        name: Node info
        run: node -p process
      -
        name: NPM version
        run: npm version
      -
        name: List install packages
        run: apt list --installed
      -
        name: Docker daemon conf
        run: |
          cat /etc/docker/daemon.json
      -
        name: Docker info
        run: docker info
      -
        name: Docker version
        run: docker version
      -
        name: Cgroups
        run: |
          sudo apt-get install -y cgroup-tools
          lscgroup
      -
        name: buildx version
        run: docker buildx version
      -
        name: containerd version
        run: containerd --version
      -
        name: Docker images
        run: docker image ls
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v2
